name: Branch Protection Rules

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  protection:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Code Quality Checks
      run: |
        pip install black flake8 mypy
        black --check .
        flake8 .
        mypy .
    - name: Security Scan
      uses: anchore/scan-action@v2
    - name: Test Coverage
      run: |
        pip install pytest pytest-cov
        pytest --cov=./ --cov-report=xml